name: Publish CV

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - name: Rename PDF
        run: mv main.pdf rahul_rameshbabu_cv_${{ github.ref_name }}.pdf
        if: startsWith(github.ref, 'refs/tags/')
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            rahul_rameshbabu_cv_${{ github.ref_name }}.pdf
            LICENSE.md
    permissions:
      contents: write
